"""empty message

Revision ID: b1402e4bb6df
Revises: a32394f349dd
Create Date: 2024-04-08 03:26:39.046350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1402e4bb6df'
down_revision = 'a32394f349dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_lockout_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('account_lockout_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
