name: Build and deploy Python app to Azure Web App
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: windows-latest
 
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
 
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'
 
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'opp-tracker-app'
        package: '.'
 
    - name: 'Logout of Azure CLI'
      run: |
        az logout
