name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.12.2

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: https://opp-tracker-app.azurewebsites.net

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'opp-tracker-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './website'

    - name: Logout of Azure CLI
      run: az logout
